# -*- coding: utf-8 -*-
"""VAE_Model_Thesis_STL_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tg-LYm4X8wc_r64Yg9UGMen6MhLtLiMb

# **VAE Model using STL-10 Dataset**
"""

# This is the General Code

"""### **Libraries**"""

# Commented out IPython magic to ensure Python compatibility.
import warnings
warnings.filterwarnings("ignore")

# Debugger
import pdb

import time

# math and numpy
import itertools
import decimal
import mpmath
import math
import numpy as np
import random

# pandas
import pandas as pd
from pandas import DataFrame
from collections import Counter

# matplot
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from IPython import display
display.set_matplotlib_formats("svg")
# %matplotlib inline
import matplotlib.patches as mpatches

# scipy
import scipy.linalg as la
from scipy.stats import entropy
from scipy.stats import norm
from scipy.stats import multivariate_normal
import scipy.io as scio

# sklearn
from sklearn import datasets
from sklearn import metrics
from sklearn.mixture import GaussianMixture
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.cluster import KMeans
from sklearn.metrics import normalized_mutual_info_score, adjusted_rand_score, accuracy_score
from scipy.optimize import linear_sum_assignment
import seaborn as sns
from sklearn.manifold import TSNE
from sklearn.datasets import load_digits
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler


# torch
import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from torch.optim.lr_scheduler import StepLR
import torchvision.transforms as transforms
import torchvision.datasets as datasets
from torch.utils.data import DataLoader, TensorDataset
from torchvision.utils import make_grid
from torch.distributions.multivariate_normal import MultivariateNormal
from torch.distributions.normal import Normal
from torch.distributions.mixture_same_family import MixtureSameFamily
from torch.distributions.categorical import Categorical
from torch.distributions.wishart import Wishart
from torch.distributions.dirichlet import Dirichlet
from torch.distributions import Bernoulli
from torch.utils.data import Dataset
import torchvision.models as models
from torchvision.models import resnet50
from torchvision.datasets import STL10

"""### **Device**"""

# start_time = time.time()
device=torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
print("Device:", device, "\n")
print("PyTorch Version:", torch.__version__, "\n")
print("Total Number of GPUs: ", torch.cuda.device_count())

"""## **Hyperparameters**"""

# VAE Part
num_epochs=2000
learning_rate=1e-4
step_size=20
weight_decay=1e-5
input_dim=2048
encoder_hidden_dim_1=500
encoder_hidden_dim_2=500
encoder_hidden_dim_3=2000
latent_dim=10
decoder_hidden_dim_1=2000
decoder_hidden_dim_2=500
decoder_hidden_dim_3=500
output_dim=2048
train_batch_size=100
test_batch_size=100
gamma=0.9


# GMM Part
num_components=10
num_iterations=20
epsilon=1e-10
decimal.getcontext().prec = 28
clustering_method="GMM"
covariance_type="full"
# covariance_type="diag"
# clustering method="K_Means"

# Set seeds for NumPy, PyTorch, and Python's random module
random_seed=5
np.random.seed(random_seed)
torch.manual_seed(random_seed)
torch.cuda.manual_seed(random_seed)
random.seed(random_seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


# Early Stopping
max_patience=num_epochs+1
best_test_loss=float("inf")
patience_counter=0

# File Name
Dataset_name = "STL_10"
Model = "VAE"
Model_name= f"{Model}_{clustering_method}_{covariance_type}_{random_seed}_{Dataset_name}"

"""# **STL-10 Dataset**

### **Summary of Dataset**
"""

data_dir = '~/Desktop/STL_10_Dataset/STL-10'
t = transforms.Compose([
    transforms.Resize(224),  # Adjust to ResNet-50 input size (224x224)
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
# Create STL-10 data loaders for training and testing
train_dataset = STL10(data_dir, split='train', transform=t, download=True)
test_dataset = STL10(data_dir, split='test', transform=t, download=True)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# Step 2: Load a pre-trained ResNet-50 model with average pooling
model = models.resnet50(pretrained=True)

# Remove the classification head
model = torch.nn.Sequential(*list(model.children())[:-2])

# Add an average pooling layer

avg_pool = torch.nn.AdaptiveAvgPool2d(1)
model = torch.nn.Sequential(model, avg_pool)
model = model.to(device)
model.eval()

# Step 3: Feature Extraction
def extract_features(dataloader):
    features = []
    labels = []

    for images, labels_batch in dataloader:
        with torch.no_grad():
            images = images.to(device)
            features_batch = model(images)
            features_batch = features_batch.view(features_batch.size(0), -1)  # Flatten feature map to a vector
            features.append(features_batch)
            labels.append(labels_batch)
    features = torch.cat(features, dim=0)
    labels = torch.cat(labels, dim=0)
    return features, labels

# Extract features from the training and testing datasets
train_features, train_labels = extract_features(train_loader)
test_features, test_labels = extract_features(test_loader)

# Step 4: Save the Features and labels to NumPy arrays.
np.save('train_features.npy', train_features.cpu().numpy())  # Move data back to CPU for saving
np.save('train_labels.npy', train_labels.cpu().numpy())
np.save('test_features.npy', test_features.cpu().numpy())
np.save('test_labels.npy', test_labels.cpu().numpy())

# Paths to feature and label files
train_features_file = 'train_features.npy'
train_labels_file = 'train_labels.npy'
test_features_file = 'test_features.npy'
test_labels_file = 'test_labels.npy'


class CustomDataset(Dataset):
    def __init__(self, features_file, labels_file):
        self.data = torch.tensor(np.load(features_file))
        self.targets = torch.tensor(np.load(labels_file))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        feature = self.data[index]
        label = self.targets[index]
        return feature, label

"""### **Summary of Dataset**"""


trainset  = CustomDataset(test_features_file, test_labels_file)
testset = CustomDataset(train_features_file, train_labels_file)


print("Training Set Size: ", len(trainset), "\n")
print("Test Set Size: ", len(testset), "\n")
print("Maximum Training Pixel: ", torch.max(trainset.data), "\n")
print("Minimum Training Pixel: ", torch.min(trainset.data), "\n")
print("Maximum Training Value: ", torch.max(trainset[0][0]), "\n")
print("Minimum Training Value: ", torch.min(trainset[0][0]), "\n")
print("5th Training Target: ", trainset[5][1], "\n")
print("First Training Example: \n\n", trainset.data[0].shape, "\n")
print("First Training Targets: \n\n", trainset.targets[0], "\n")

"""### **Data Loader**"""

train_loader=DataLoader(trainset, batch_size=train_batch_size, shuffle=True)
test_loader=DataLoader(testset, batch_size=test_batch_size, shuffle=False)
print("Number of Iterations in Each Epoch (Training):", len(train_loader))
print("Number of Iterations in Each Epoch (Test):", len(test_loader))

with open(f'Summary_Statistics_Training_{Dataset_name}.txt', 'w') as file:
    file.write(f"Training Set Size: {len(trainset)}\n")
    file.write(f"Maximum Training Pixel: {torch.max(trainset.data)}\n")
    file.write(f"Minimum Training Pixel: {torch.min(trainset.data)}\n")
    file.write(f"Maximum Training Value: {torch.max(trainset[0][0])}\n")
    file.write(f"Minimum Training Value: {torch.min(trainset[0][0])}\n")
    file.write(f"5th Training Target: {trainset[5][1]}\n")
    file.write(f"First Training Example: {trainset.data[0].shape}\n")
    file.write(f"First Training Targets: {trainset.targets[0]}\n")
    file.write(f"Number of Iterations in Each Epoch (Training): {len(train_loader)}\n")


with open(f'Summary_Statistics_Test_{Dataset_name}.txt', 'w') as file:
    file.write(f"Test Set Size: {len(testset)}\n")
    file.write(f"Maximum Test Pixel: {torch.max(testset.data)}\n")
    file.write(f"Minimum Test Pixel: {torch.min(testset.data)}\n")
    file.write(f"Maximum Test Value: {torch.max(testset[0][0])}\n")
    file.write(f"Minimum Test Value: {torch.min(testset[0][0])}\n")
    file.write(f"5th Test Target: {testset[5][1]}\n")
    file.write(f"First Test Example Shape: {testset.data[0].shape}\n")
    file.write(f"First Test Targets Shape: {testset.targets[0]}\n")
    file.write(f"Number of Iterations in Each Epoch (Test): {len(test_loader)}\n")

# for epoch in range(1):
#   for i, (X, y) in enumerate(train_loader, 1):
#     print(f"\n\n Epoch {epoch+1}, \t Batch {i}, \n\n Target: \n {y}, \n Input: \n {X}, \n Training Image Shape \n\n {X.shape} {X.dtype}, \n \n Training Target Shape \n\n {y.shape} {y.dtype} \n \n")
#     # print("-"*150)
#     break

"""# **Functions**

### **Clustering Accuracy with Linear Assignment**
"""

def cluster_acc_with_assignment(y_true, y_pred):
    y_true = y_true.astype(np.int64)
    assert y_pred.size == y_true.size
    D = max(y_pred.max(), y_true.max()) + 1
    w = np.zeros((D, D), dtype=np.int64)
    for i in range(y_pred.size):
        w[y_pred[i], y_true[i]] += 1
    row_ind, col_ind = linear_sum_assignment(w.max() - w)

    new_predicted_labels = np.array([col_ind[i] for i in y_pred])
    accuracy = sum([w[row, col] for row, col in zip(row_ind, col_ind)]) * 1.0 / y_pred.size
    return accuracy, new_predicted_labels

"""# **VAE Model**

### **Encoder Class**
"""

class Encoder(nn.Module):
  def __init__(self):
    super(Encoder, self).__init__()
    self.encoder = nn.Sequential(
        nn.Linear(input_dim, encoder_hidden_dim_1),
        nn.ReLU(),
        nn.Linear(encoder_hidden_dim_1, encoder_hidden_dim_2),
        nn.ReLU(),
        nn.Linear(encoder_hidden_dim_2, encoder_hidden_dim_3),
        nn.ReLU(),
    )
    self.mu_layer = nn.Linear(encoder_hidden_dim_3, latent_dim)
    self.log_var_layer = nn.Linear(encoder_hidden_dim_3, latent_dim)

  def forward(self, x):
    x = self.encoder(x)
    return self.mu_layer(x), self.log_var_layer(x)

"""### **Decoder Class**"""

class Decoder(nn.Module):
  def __init__(self):
    super(Decoder, self).__init__()
    self.decoder = nn.Sequential(
        nn.Linear(latent_dim, decoder_hidden_dim_1),
        nn.ReLU(),
        nn.Linear(decoder_hidden_dim_1, decoder_hidden_dim_2),
        nn.ReLU(),
        nn.Linear(decoder_hidden_dim_2, decoder_hidden_dim_3),
        nn.ReLU(),
        nn.Linear(decoder_hidden_dim_3, output_dim),
        # nn.Sigmoid()
    )
  def forward(self, z):
    return self.decoder(z)

"""### **VAE Class**"""

class VAE(nn.Module):
  def __init__(self):
    super(VAE, self).__init__()
    self.encoder=Encoder()
    self.decoder=Decoder()

  def reparameterize(self, mu, log_var):
    if self.training:
      sigma=torch.exp(0.5*log_var)
      eps=torch.randn_like(sigma)
      return mu+eps*sigma
    else:
      return mu

  def forward(self,x):
    x=x.view(-1, input_dim)
    encoder_mu, encoder_logvar=self.encoder(x)
    latent_z=self.reparameterize(encoder_mu, encoder_logvar)
    decoder_mu=self.decoder(latent_z)
    return decoder_mu, latent_z, encoder_mu, encoder_logvar

"""### **VAE Model and Optimizer**"""

model=VAE().to(device)
optimizer = optim.Adam(model.parameters(), lr=learning_rate)
scheduler = StepLR(optimizer, step_size=step_size, gamma=gamma)
print(model)
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print('\n \n Number of Estimated Parameters: %d' % num_params)

model_info=str(model)
file_path=f"Model_Architecture_{Model_name}_{Dataset_name}.txt"
with open(file_path, "w") as file:
    file.write("Model Architecture:\n")
    file.write(model_info)
    file.write("\n\nNumber of Estimated Parameters: %d\n" % num_params)

"""### **Shape of Encoder, Decoder and Prior**"""

# for train_features,train_labels in train_loader:
#   train_features=train_features.reshape(-1, input_dim)
#   train_features=train_features.to(device)
#   decoder_mu, latent_z, latent_mu, latent_logvar=model(train_features)
#   decoder_mu=decoder_mu.to(device)
#   print("\nFeatures shape: \n", train_features.shape)
#   print("\nDecoder mu shape: \n", decoder_mu.shape)
#   print("\nLatent vector shape: \n", latent_z.shape)
#   print("\nEncoder mu_k shape: \n", latent_mu.shape)
#   print("\nEncoder logvar_k shape: \n", latent_logvar.shape)
#   # Encoder Likelihood: Shape [B, K, M]
#   encoder_dist=Normal(loc=latent_mu, scale=torch.exp(0.5*latent_logvar))
#   encoder_log_prob=encoder_dist.log_prob(latent_z).sum(dim=1)
#   print("\nEncoder log probability shape:\n", encoder_log_prob.shape)
#   # Decoder Likelihood: Shape [B, K, D]
#   decoder_dist=Normal(loc=decoder_mu, scale=torch.ones_like(decoder_mu))
#   decoder_log_prob=decoder_dist.log_prob(train_features).sum(dim=1)
#   print("\nDecoder log probability shape:\n", decoder_log_prob.shape)
#   break

"""# **Model Training**

### **Backpropagation and Parameter Updates**
"""

Training_Losses=[]
Test_Loss=[]
True_Labels=[]
Latent_embeddings=[]

# GMM Part
Accuracy=[]
Mean_Accuracy=[]
STD_Accuracy=[]
NMI=[]
ARI=[]
Posterior_EM=[]
Updated_Labels=[]

print(f"Training and Testing {Model_name} Model: {Dataset_name} Dataset: \n\n")

for epoch in range(num_epochs):

  ## Training Step
  model.train()
  Training_Losses.append(0)
  num_batches=0

  for training_features, _ in train_loader:
    optimizer.zero_grad()
    training_features=training_features.reshape(-1, input_dim)
    training_features=training_features.to(device)

    decoder_mu, latent_z, latent_mu, latent_logvar=model(training_features)
    decoder_mu=decoder_mu.to(device)                                             # [B, K, D]
    batch_size, batch_dim = training_features.shape

    # Encoder Likelihood: [B, M]

    q_z_x= Normal(loc=latent_mu, scale=torch.exp(0.5*latent_logvar))
    log_q_z_x = torch.sum(q_z_x.log_prob(latent_z))


    # Standard Prior Likelihood: [B, M]

    p_z=Normal(loc=torch.zeros_like(latent_mu), scale=torch.ones_like(latent_logvar))
    log_p_z=torch.sum(p_z.log_prob(latent_z))

    # Decoder Likelihood: [B, D]

    ############################# Real-Valued Data #############################

    # log_p_x_z = -F.mse_loss(input=decoder_mu, target=training_features, reduction="none")
    # log_p_x_z = torch.sum(log_p_x_z, dim=2)

    p_x_z=Normal(loc=decoder_mu, scale=torch.ones_like(decoder_mu))
    log_p_x_z=torch.sum(p_x_z.log_prob(training_features))

    ############################################################################

    ELBO=(log_p_x_z-log_q_z_x+log_p_z)                                           # [B, K]


    # Total Loss
    Total_Loss = -ELBO

    # Backpropagation
    Total_Loss.backward()
    optimizer.step()
    num_batches+=1
    Training_Losses[-1]+=Total_Loss.item()

  # Update the Learning Rate
  scheduler.step()

  # Average Losses
  Training_Losses[-1]/= num_batches

  ## Evaluation Step
  model.eval()
  Final_Test_Loss=0.0
  number_of_batches=0
  latent_space=[]
  ground_truth_labels=[]

  # GMM Part
  simulated_accuracies = []
  simulated_nmi = []
  simulated_ari = []
  simulated_predicted_labels = []
  simulated_posterior_probabilities_gmm = []
  reconstructions = []
  original_image = []


  with torch.no_grad():
    for test_features, test_labels in test_loader:

      test_features=test_features.reshape(-1, input_dim)
      test_features=test_features.to(device)
      test_labels=test_labels.to(device)

      decoder_mu_test, latent_z_test, latent_mu_test, latent_logvar_test=model(test_features)
      decoder_mu_test=decoder_mu_test.to(device)
      batch_size, batch_dim = test_features.shape

      latent_space.append(latent_z_test)
      ground_truth_labels.append(test_labels.cpu().numpy())

      # Encoder Likelihood: Shape [B, M]

      q_z_x_test = Normal(loc=latent_mu_test, scale=torch.exp(0.5*latent_logvar_test))
      log_q_z_x_test = torch.sum(q_z_x_test.log_prob(latent_z_test))


      # Standard Prior Likelihood: [B, M]

      p_z_test=Normal(loc=torch.zeros_like(latent_mu_test), scale=torch.ones_like(latent_logvar_test))
      log_p_z_test=torch.sum(p_z_test.log_prob(latent_z_test))

      # Decoder log-Likelihood

      ############################# Real-Valued Data ###########################


      # log_p_x_z_test= -F.mse_loss(input=decoder_mu_test, target=test_features, reduction="sum")

      p_x_z_test=Normal(loc=decoder_mu_test, scale=torch.ones_like(decoder_mu_test))
      log_p_x_z_test=torch.sum(p_x_z_test.log_prob(test_features))

      ######################### Test ELBO  #########################

      ELBO_test=(log_p_x_z_test-log_q_z_x_test+log_p_z_test)

      # Total Loss

      Total_Test_Loss = -ELBO_test
      Final_Test_Loss+= Total_Test_Loss.item()
      number_of_batches+= 1

      reconstructions.append(decoder_mu_test)
      original_image.append(test_features)

    # Average Loss
    Final_Test_Loss/=number_of_batches
    Test_Loss.append(Final_Test_Loss)

    # Latent Space
    latent_space=torch.cat(latent_space, dim=0).detach().cpu().numpy()
    Latent_embeddings.append(latent_space)


    # True Labels
    ground_truth_labels_numpy = np.concatenate(ground_truth_labels)
    True_Labels.append(ground_truth_labels_numpy)

    ################## Clustering using K-means#################################

    # for i in range(num_iterations):
    #   # seed = np.random.randint(0, 100)
    #   kmeans = KMeans(n_clusters=num_components, random_state=i)
    #   predicted_labels = kmeans.fit(latent_space).labels_
    #   nmi= normalized_mutual_info_score(ground_truth_labels_numpy, predicted_labels)
    #   ari= adjusted_rand_score(ground_truth_labels_numpy, predicted_labels)
    #   new_accuracy, new_predicted_labels = cluster_acc_with_assignment(ground_truth_labels_numpy,
    #                                                                             predicted_labels)
    #   simulated_accuracies.append(new_accuracy)
    #   simulated_nmi.append(nmi)
    #   simulated_ari.append(ari)
    #   simulated_predicted_labels.append(new_predicted_labels)

    # average_accuracy = np.mean(simulated_accuracies)
    # max_accuracy = np.max(simulated_accuracies)
    # sd_accuracy = np.std(simulated_accuracies)
    # Accuracy.append(max_accuracy)
    # Mean_Accuracy.append(average_accuracy)
    # STD_Accuracy.append(sd_accuracy)
    # best_accuracy_index = simulated_accuracies.index(np.max(simulated_accuracies))
    # Updated_Labels.append(simulated_predicted_labels[best_accuracy_index])
    # NMI.append(simulated_nmi[best_accuracy_index])
    # ARI.append(simulated_ari[best_accuracy_index])

    ##################Clustering using Gaussian Mixture Model###################
    for i in range(num_iterations):
      # seed = np.random.randint(0, 100)
      gmm = GaussianMixture(n_components=num_components, covariance_type=covariance_type, random_state=i)
      predicted_labels = gmm.fit_predict(latent_space)
      posterior_probabilities_gmm = gmm.predict_proba(latent_space)
      simulated_posterior_probabilities_gmm.append(posterior_probabilities_gmm)
      nmi = normalized_mutual_info_score(ground_truth_labels_numpy, predicted_labels)
      ari = adjusted_rand_score(ground_truth_labels_numpy, predicted_labels)
      new_accuracy, new_predicted_labels = cluster_acc_with_assignment(ground_truth_labels_numpy,
                                                                                predicted_labels)
      simulated_accuracies.append(new_accuracy)
      simulated_nmi.append(nmi)
      simulated_ari.append(ari)
      simulated_predicted_labels.append(new_predicted_labels)

    average_accuracy = np.mean(simulated_accuracies)
    max_accuracy = np.max(simulated_accuracies)
    sd_accuracy = np.std(simulated_accuracies)
    Accuracy.append(max_accuracy)
    Mean_Accuracy.append(average_accuracy)
    STD_Accuracy.append(sd_accuracy)
    best_accuracy_index = simulated_accuracies.index(np.max(simulated_accuracies))
    Updated_Labels.append(simulated_predicted_labels[best_accuracy_index])
    Posterior_EM.append(simulated_posterior_probabilities_gmm[best_accuracy_index])
    NMI.append(simulated_nmi[best_accuracy_index])
    ARI.append(simulated_ari[best_accuracy_index])
    ####################################################################################################################

    if (epoch+1)%5==0:
        print(f"\n Step: [{epoch+1}/{num_epochs}] \t  Training Loss: {Training_Losses[-1]: 0.2f} \t Test Loss: {Final_Test_Loss: 0.2f} \
        \t Accuracy (GMM): {max_accuracy: 0.2f} \t NMI (GMM): {simulated_nmi[best_accuracy_index]: 0.2f} \t LR: {scheduler.get_last_lr()[0]:0.6f}")

"""### **Store All the Results**"""

hyperparameter_file_path = f'Hyperparameters_{Model_name}_{Dataset_name}.txt'
with open(hyperparameter_file_path, 'w') as file:
  file.write(f"Dataset: {Dataset_name}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Model Name: {Model_name}\n")
  file.write(f"==================================================================\n")
  file.write(f"{Model_name} Part:\n")
  file.write(f"==================================================================\n")
  file.write(f"Random Seed = {random_seed}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Device = {device}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Number of Epochs = {num_epochs}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Learning Rate = {learning_rate}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Step Size = {step_size}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Input Dimension = {input_dim}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Encoder Hidden Dimension 1 = {encoder_hidden_dim_1}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Encoder Hidden Dimension 2 = {encoder_hidden_dim_2}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Encoder Hidden Dimension 3 = {encoder_hidden_dim_3}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Latent Dimension = {latent_dim}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Decoder Hidden Layer 1 = {decoder_hidden_dim_1}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Decoder Hidden Layer 2 = {decoder_hidden_dim_2}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Decoder Hidden Layer 3 = {decoder_hidden_dim_3}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Output Dimension = {output_dim}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Weight Decay = {weight_decay}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Batch Size (Training) = {train_batch_size}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Batch Size (Test) = {test_batch_size}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"gamma = {gamma}\n")
  file.write(f"==================================================================\n")


  file.write("\nGMM Part:\n")
  file.write(f"==================================================================\n")
  file.write(f"Number of Components= {num_components}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Covariance Matrix= {covariance_type}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Number of Iterations= {num_iterations}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Epsilon = {epsilon}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Precision = {decimal.getcontext().prec }\n")
  file.write(f"==================================================================\n")

  file.write("\nEarly Stopping:\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Maximum Patience = {max_patience}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Best Test Loss = {best_test_loss}\n")
  file.write(f"--------------------------------------------\n")
  file.write(f"Patience Counters = {patience_counter}\n")
  file.write(f"==================================================================\n")

  file.write("\nLoss Functions:\n")
  file.write(f"==================================================================\n")
  file.write(f"Decoder Loss (Training) = {log_p_x_z}\n")
  file.write(f"=============================================================================================\n")
  file.write(f"Encoder Loss (Training) = {q_z_x}\n")
  file.write(f"=============================================================================================\n")
  file.write(f"Decoder Loss (Test) = {log_p_x_z_test}\n")
  file.write(f"=============================================================================================\n")
  file.write(f"Encoder Loss (Test) = {q_z_x_test}\n")
  file.write(f"=============================================================================================\n")

"""### **Save Results**"""

with open(f'Training_Losses_{Model_name}_{Dataset_name}.txt', 'w') as file:
    for loss in Training_Losses:
        file.write(str(loss) + '\n')

with open(f'Test_Losses_{Model_name}_{Dataset_name}.txt', 'w') as file:
  for loss1 in Test_Loss:
    file.write(str(loss1) + '\n')

with open(f'Accuracy_GMM_{Model_name}_{Dataset_name}.txt', 'w') as file:
  for loss4 in Accuracy:
    file.write(str(loss4) + '\n')

with open(f'NMI_GMM_{Model_name}_{Dataset_name}.txt', 'w') as file:
  for loss5 in NMI:
    file.write(str(loss5) + '\n')

with open(f'ARI_GMM_{Model_name}_{Dataset_name}.txt', 'w') as file:
  for loss6 in ARI:
    file.write(str(loss6) + '\n')

"""### **Model Parameters**"""

# print(f"Model Parameters: \n\n", model.parameters)
param_list = [*model.parameters()]
# print(f"\n Parameter List: \n\n", param_list)

results_file_path = f'True_Predicted_{Model_name}_{Dataset_name}.txt'

with open(results_file_path, 'w') as file:
    true_labels_frequency = Counter(True_Labels[-1])
    file.write("\nTrue Labels Frequency:\n")
    file.write(str(true_labels_frequency) + '\n')

    predicted_labels_frequency = Counter(Updated_Labels[-1])
    file.write("\nPredicted Labels Frequency:\n")
    file.write(str(predicted_labels_frequency) + '\n')

results_file_path_2 = f'Model_Parameters_{Model_name}_{Dataset_name}.txt'
with open(results_file_path_2, 'w') as file:
    Parameters = param_list
    file.write("\nParameter List:\n")
    file.write(str(Parameters) + '\n')

"""# **Results**

### **Clustering Accuracy**
"""

print("\n Loss:")
print("-"*50)
print("\n Final Training Loss:", Training_Losses[-1])
print("\n Final Test Loss:", Test_Loss[-1])
print("-"*50)
print("\n Clustering Results:")
print(f"\n Clustering accuracy: {Accuracy[-1]: 0.3f}")
print(f'\n NMI: {NMI[-1]: 0.2f}')
print(f'\n ARI: {ARI[-1]: 0.2f}')
print("-"*50)

overall_avg_accuracy = np.mean(Accuracy)
overall_std_accuracy = np.std(Accuracy)
print("Overall Mean Accuracy", overall_avg_accuracy, "\n")
print("Overall STD Accuracy", overall_std_accuracy, "\n")

text_to_save =f"\n Final Training Loss: {Training_Losses[-1]}\n" \
              f"\n Final Test Loss: {Test_Loss[-1]}\n\n" \
              f"\n Clustering Results:\n\n"\
              f"\n Accuracy: {Accuracy[-1]: 0.3f}\n"\
              f"\n NMI: {NMI[-1]: 0.3f}\n"\
              f"\n ARI: {ARI[-1]: 0.3f}\n"\
              f"\n Average Accuracy: {overall_avg_accuracy}\n"\
              f"\n STD Accuracy: {overall_std_accuracy}\n"\


file_path = f"Results_{Model_name}_{Dataset_name}.txt"
with open(file_path, "w") as text_file:
    text_file.write(text_to_save)

"""### **Maximum Accuracies**"""

max_accuracy_indices = sorted(range(len(Accuracy)), key=lambda i: Accuracy[i], reverse=True)[:10]
max_accuracy_values = [Accuracy[i] for i in max_accuracy_indices]
with open(f'Accuracy_Highest_{Model_name}_{Dataset_name}.txt', 'w') as file:
    for idx, accuracy in zip(max_accuracy_indices, max_accuracy_values):
        result_line = f"Index: {idx}, \t Accuracy: {accuracy:.4f}"
        file.write(result_line + '\n')
        print(result_line)

"""### **True and Predicted Labels**"""

print(f"\n True Labels Frequency:\n\n {Counter(True_Labels[-1])}")
print(f"\n GMM Labels Frequency:\n{Counter(Updated_Labels[-1])}")

"""# **Graphs**

###**STD Accuracy**
"""

x=np.linspace(1, len(STD_Accuracy), len(STD_Accuracy))
plt.figure(figsize=(8,6))
plt.xlabel("Epochs")
plt.ylabel("SD (Accuracy)")
plt.plot(x, STD_Accuracy, color="blue", linestyle="solid", linewidth=1)
plt.grid()
plt.savefig(f"SD_Accuracy_Training_{Model_name}_{Dataset_name}.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""###**Mean and Maximum Accuracy**"""

plt.figure(figsize=(8, 6))
x=np.linspace(1, len(Accuracy), len(Accuracy))
y=np.linspace(1, len(Mean_Accuracy), len(Mean_Accuracy))
plt.plot(x, Accuracy, label='Maximum Accuracy', color="blue", linestyle="solid", linewidth=1,  marker='o')
plt.plot(y, Mean_Accuracy, label='Mean_Accuracy', color="green", linestyle="solid", linewidth=1,  marker='x')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(loc="best")
plt.grid()
plt.savefig(f"Mean_Maximum_{Model_name}_{Dataset_name}.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""###**Mean and Maximum Accuracy (After 10 epochs)**"""

list1=Accuracy
list2=Mean_Accuracy
indices = list(range(0, len(list1), 10))
accuracy1 = [list1[i] for i in indices]
accuracy2 = [list2[i] for i in indices]
plt.figure(figsize=(8, 6))
plt.plot(indices, accuracy1, label='Maximum Accuracy', color="blue", linestyle="solid", linewidth=1,  marker='o')
plt.plot(indices, accuracy2, label='Mean_Accuracy', color="green", linestyle="solid", linewidth=1,  marker='x')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend(loc="best")
plt.grid()
plt.savefig(f"Mean_Maximum_{Model_name}_{Dataset_name}_10_epochs.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""### **Training Losses and Test Losses**"""

plt.figure(figsize=(8, 6))
x=np.linspace(1, len(Training_Losses), len(Training_Losses))
y=np.linspace(1, len(Test_Loss), len(Test_Loss))
plt.plot(x, Training_Losses, label='Training Losses', color="blue", linestyle="solid", linewidth=1)
plt.plot(y, Test_Loss, label='Test Losses', color="green", linestyle="solid", linewidth=1)
plt.xlabel('Epochs')
plt.ylabel('Negative ELBO')
# plt.title('Training and Test Losses')
plt.legend(loc="best")
plt.grid()
plt.savefig(f"Training_Test_Loss_{Model_name}_{Dataset_name}.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""### **Negative ELBO (Training Loss)**"""

x=np.linspace(1, len(Training_Losses), len(Training_Losses))
plt.figure(figsize=(8, 6))
plt.xlabel("Epochs")
plt.ylabel("Negative ELBO (Training Losses)")
plt.plot(x, Training_Losses, color="blue", linestyle="solid", linewidth=1)
plt.grid()
plt.savefig(f"Negative_ELBO_Training_Loss_{Model_name}_{Dataset_name}.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""### **Negative ELBO (Test Loss)**"""

x=np.linspace(1, len(Test_Loss), len(Test_Loss))
plt.figure(figsize=(8, 6))
plt.xlabel("Epochs")
plt.ylabel("Negative ELBO (Test Loss)")
plt.plot(x, Test_Loss, color="blue", linestyle="solid", linewidth=1)
plt.grid()
plt.savefig(f"Negative_ELBO_Test_Loss_{Model_name}_{Dataset_name}.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""### **Accuracy (GMM)**"""

x=np.linspace(1, len(Accuracy), len(Accuracy))
plt.figure(figsize=(8, 6))
plt.xlabel("Epochs")
plt.ylabel('Clustering Accuracy')
plt.plot(x, Accuracy, color="blue", linestyle="solid", linewidth=1)
plt.grid()
plt.savefig(f"Accuracy_{Model_name}_{Dataset_name}_GMM.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""### **NMI (GMM)**"""

x=np.linspace(1, len(NMI), len(NMI))
plt.figure(figsize=(8, 6))
plt.xlabel("Epochs")
plt.ylabel('Normalized Mutual Information')
plt.plot(x, NMI, color="blue", linestyle="solid", linewidth=1)
plt.grid()
plt.savefig(f"NMI_{Model_name}_{Dataset_name}.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""### **ARI (GMM)**"""

x=np.linspace(1, len(ARI), len(ARI))
plt.figure(figsize=(8, 6))
plt.xlabel("Epochs")
plt.ylabel('Adjusted Rand Index')
plt.plot(x, ARI, color="blue", linestyle="solid", linewidth=1)
plt.grid()
plt.savefig(f"ARI_GMM_{Model_name}_{Dataset_name}.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""# **Confusion Matrix and t-SNE**

### **Confusion Matrix (GMM)**
"""

conf_matrix = confusion_matrix(True_Labels[-1], Updated_Labels[-1])
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", cbar=False)
plt.xlabel("Predicted Labels")
plt.ylabel("True Labels")
# plt.title("Confusion Matrix")
plt.savefig(f"Confusion_Matrix_{Model_name}_{Dataset_name}_GMM.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""### **t-SNE Visualization**"""

latent_space_recoded=torch.tensor(Latent_embeddings[-1], dtype=torch.float32)
# tsne = TSNE(n_components=2, perplexity=5, random_state=random_seed)
tsne = TSNE(n_components=2, random_state=random_seed)
latent_tsne = tsne.fit_transform(latent_space_recoded)
plt.figure(figsize=(10, 10))
cmap = plt.cm.get_cmap('rainbow', len(np.unique(Updated_Labels[-1])))

scatter = plt.scatter(latent_tsne[:, 0], latent_tsne[:, 1], c=Updated_Labels[-1], cmap='rainbow')
plt.colorbar(scatter)
# plt.title('Visualization of Latent Space with Clusters')
plt.xlabel('Latent Embeddings (1)')
plt.ylabel('Latent Embeddings (2)')
# plt.grid(True)
# Create legend handles for each cluster
legend_handles = [mpatches.Patch(color=cmap(i), label=f'Cluster {i}') for i in np.unique(Updated_Labels[-1])]
plt.legend(handles=legend_handles, loc='best')

plt.savefig(f"t-SNE_Visualization_{Model_name}_{Dataset_name}_GMM.pdf", format="pdf", bbox_inches="tight")
plt.close()

"""### **Result: Posterior Probabilities (EM algorithm)**"""

posterior_probabilities_em=Posterior_EM[-1]
predicted_labels = Updated_Labels[-1]
true_labels = True_Labels[-1]
num_cols = posterior_probabilities_em.shape[1]
column_labels = [f'c_{i}_em' for i in range(num_cols)]
df_em = pd.DataFrame({column_labels[i]: np.round(posterior_probabilities_em[:, i], 2) for i in range(num_cols)})
posterior_columns_em = [col for col in df_em.columns if col.startswith('c_')]
max_values = df_em[posterior_columns_em].max(axis=1)
second_max_values = df_em[posterior_columns_em].apply(lambda row: sorted(row)[-2], axis=1)
df_em['difference'] = max_values - second_max_values
df_em['y_hat_em']= predicted_labels
df_em['True_y']= true_labels
df_em['Correct'] = df_em['y_hat_em'] == df_em['True_y']
df_em_styled = df_em.style.set_properties(**{'border-bottom': '1px solid black'})
df_em.to_csv(f'Posterior_Probability_{Model_name}_{Dataset_name}.csv', index=False)

print(f"Experiment Completed on Model: {Model_name} and {Dataset_name} Dataset")